/**
 * AI Foundation learning event vocabulary.
 * Extends Sprint 29 marketplace events with intent/knowledge signals.
 */

export const AI_LEARNING_EVENT_TYPES = [
  "intent_suggested",
  "intent_confirmed",
  "intent_corrected",
  "category_changed",
  "knowledge_hit",
  "knowledge_miss",
  "llm_invoked",
  "provider_accepted",
  "provider_declined",
  "job_completed",
  "memory_recorded",
  "urgency_corrected",
  "workflow_recommended",
  "workflow_overridden",
  "match_ranked",
  "match_accepted",
  "match_rejected",
  "question_answered",
  "intent_cached",
  "dispatch_planned",
  "dispatch_exposed",
  "capacity_skipped",
  "route_boosted",
  "response_predicted",
  "eta_predicted",
  "prediction_compared",
  "reputation_updated",
  "job_analyzed",
  "job_prep_shown",
  "job_duration_compared",
  "job_materials_compared",
  "job_complexity_compared",
  "multi_service_detected",
  "vision_analyzed",
  "vision_cached",
  "vision_confirmed",
  "vision_corrected",
  "vision_fused",
  "vision_contradiction",
  "vision_damage_compared",
  "vision_tools_compared",
  "vision_materials_compared",
  "voice_transcribed",
  "voice_cached",
  "voice_confirmed",
  "voice_corrected",
  "voice_transcript_edited",
  "voice_fused",
  "voice_contradiction",
  "voice_language_detected",
  "voice_stt_failed",
  "voice_category_compared",
  "assistant_shown",
  "assistant_suggestion_accepted",
  "assistant_suggestion_ignored",
  "assistant_suggestion_rejected",
  "assistant_summary_generated",
  "assistant_summary_rated",
  "assistant_offer_compared",
  "assistant_appointment_briefed",
  "assistant_after_job",
  "assistant_reminder_sent",
  "assistant_reminder_acted",
  "assistant_context_updated",
  "forecast_correct",
  "forecast_incorrect",
  "capacity_prediction",
  "demand_prediction",
  "wait_time_prediction",
  "notification_clicked",
  "recommendation_followed",
  "balance_action_recommended",
  "prediction_calibrated",
  "automation_suggested",
  "automation_executed",
  "automation_confirmed",
  "automation_rejected",
  "automation_modified",
  "automation_reversed",
  "automation_blocked_safety",
  "workflow_run",
] as const;

export type AiLearningEventType = (typeof AI_LEARNING_EVENT_TYPES)[number];

export type AiLearningEventInput = {
  eventType: AiLearningEventType;
  providerId?: string | null;
  customerId?: string | null;
  serviceRequestId?: string | null;
  searchLogId?: string | null;
  metadata?: Record<string, unknown>;
};
