import type { PriceEstimate, ServiceKnowledgeEntry } from "@/lib/ai/jobs/types";

const SYP_DISCLAIMER_EN =
  "Estimated market range only — final quote depends on on-site inspection.";
const SYP_DISCLAIMER_AR =
  "نطاق سعري تقديري فقط — العرض النهائي يعتمد على المعاينة في الموقع.";

function syp(min: number, typical: number, max: number): PriceEstimate {
  return {
    min,
    typical,
    max,
    currency: "SYP",
    isRangeOnly: true,
    disclaimerEn: SYP_DISCLAIMER_EN,
    disclaimerAr: SYP_DISCLAIMER_AR,
  };
}

function minutes(
  min: number,
  typical: number,
  max: number,
): ServiceKnowledgeEntry["duration"] {
  return {
    minMinutes: min,
    typicalMinutes: typical,
    maxMinutes: max,
    labelEn: `${min}–${max} minutes`,
    labelAr: `${min}–${max} دقيقة`,
    unit: "minutes",
  };
}

function days(
  minDays: number,
  typicalDays: number,
  maxDays: number,
): ServiceKnowledgeEntry["duration"] {
  return {
    minMinutes: minDays * 24 * 60,
    typicalMinutes: typicalDays * 24 * 60,
    maxMinutes: maxDays * 24 * 60,
    labelEn: `${minDays}–${maxDays} days`,
    labelAr: `${minDays}–${maxDays} أيام`,
    unit: "days",
  };
}

/**
 * Seeded service knowledge — Dalily's technician-style domain intelligence.
 * Keys are stable; learning may refine duration/price aggregates in DB.
 */
export const SERVICE_KNOWLEDGE_CATALOG: ServiceKnowledgeEntry[] = [
  {
    serviceKey: "plumbing.leak.pipe",
    categorySlug: "plumbing",
    subcategory: "leak",
    typicalProblems: ["Pipe leak", "Joint drip", "Under-sink leak"],
    commonCauses: ["Worn seal", "Loose fitting", "Cracked PVC section"],
    requiredSkills: ["Pipe fitting", "Leak diagnosis"],
    typicalTools: ["Pipe wrench", "Adjustable wrench", "Sealant gun", "Cutter"],
    commonMaterials: ["Sealant", "Replacement fittings", "Pipe section", "Teflon tape"],
    duration: minutes(45, 70, 90),
    complexity: "moderate",
    emergencyCapable: true,
    certifications: [],
    price: syp(75000, 150000, 350000),
    relatedTrades: ["painting", "carpentry"],
    matchKeywords: [
      "leak",
      "pipe",
      "تسرب",
      "ماسورة",
      "أنبوب",
      "sarb",
      "غرق",
      "flood",
    ],
    workersTypical: 1,
    followUpWork: ["Drywall repair", "Repaint water-stained wall"],
  },
  {
    serviceKey: "plumbing.leak.toilet",
    categorySlug: "plumbing",
    subcategory: "toilet",
    typicalProblems: ["Toilet overflow", "Tank leak", "Running toilet"],
    commonCauses: ["Faulty flapper", "Fill valve", "Wax ring"],
    requiredSkills: ["Toilet repair"],
    typicalTools: ["Pipe wrench", "Plunger", "Screwdrivers"],
    commonMaterials: ["Flapper", "Fill valve", "Wax ring", "Teflon tape"],
    duration: minutes(30, 50, 90),
    complexity: "moderate",
    emergencyCapable: true,
    certifications: [],
    price: syp(60000, 120000, 280000),
    relatedTrades: [],
    matchKeywords: ["toilet", "مرحاض", "تواليت", "overflow", "طفح"],
    workersTypical: 1,
    followUpWork: [],
  },
  {
    serviceKey: "plumbing.kitchen.sink",
    categorySlug: "plumbing",
    subcategory: "kitchen",
    typicalProblems: ["Clogged sink", "Trap leak", "Faucet drip"],
    commonCauses: ["Grease clog", "Worn washer", "Loose trap"],
    requiredSkills: ["Drain clearing", "Faucet repair"],
    typicalTools: ["Pipe wrench", "Drain snake", "Screwdrivers"],
    commonMaterials: ["Washer", "Trap gasket", "Teflon tape"],
    duration: minutes(30, 45, 75),
    complexity: "simple",
    emergencyCapable: false,
    certifications: [],
    price: syp(50000, 100000, 220000),
    relatedTrades: [],
    matchKeywords: ["sink", "kitchen", "مطبخ", "مجلى", "faucet", "حنفية"],
    workersTypical: 1,
    followUpWork: [],
  },
  {
    serviceKey: "electrical.outlet.replace",
    categorySlug: "electrical",
    subcategory: "outlet",
    typicalProblems: ["Broken outlet", "No power at socket", "Loose socket"],
    commonCauses: ["Worn contacts", "Loose wiring", "Damaged faceplate"],
    requiredSkills: ["Socket replacement", "Safe isolation"],
    typicalTools: ["Voltage tester", "Multimeter", "Screwdrivers", "Wire stripper"],
    commonMaterials: ["Socket", "Frame", "Electrical screws", "Wire nuts"],
    duration: minutes(20, 30, 40),
    complexity: "simple",
    emergencyCapable: false,
    certifications: ["Licensed electrician recommended"],
    price: syp(40000, 80000, 150000),
    relatedTrades: [],
    matchKeywords: ["outlet", "socket", "فيش", "مقبس", "plug"],
    workersTypical: 1,
    followUpWork: [],
  },
  {
    serviceKey: "electrical.power_outage",
    categorySlug: "electrical",
    subcategory: "power_outage",
    typicalProblems: ["No electricity", "Partial outage", "Tripped breaker"],
    commonCauses: ["Tripped fuse/breaker", "Loose main", "Overloaded circuit"],
    requiredSkills: ["Panel diagnosis", "Circuit tracing"],
    typicalTools: ["Voltage tester", "Multimeter", "Screwdrivers", "Flashlight"],
    commonMaterials: ["Replacement breaker", "Fuse (if applicable)"],
    duration: minutes(30, 60, 120),
    complexity: "moderate",
    emergencyCapable: true,
    certifications: ["Licensed electrician recommended"],
    price: syp(70000, 160000, 400000),
    relatedTrades: [],
    matchKeywords: [
      "power",
      "outage",
      "كهربا",
      "انقطاع",
      "فيوز",
      "fuse",
      "breaker",
      "قاطع",
    ],
    workersTypical: 1,
    followUpWork: ["Panel upgrade if recurring overloads"],
  },
  {
    serviceKey: "electrical.safety.sparks",
    categorySlug: "electrical",
    subcategory: "safety",
    typicalProblems: ["Sparks", "Burning smell", "Hot outlet"],
    commonCauses: ["Short circuit", "Overloaded wiring", "Loose terminal"],
    requiredSkills: ["Emergency isolation", "Fault finding"],
    typicalTools: ["Voltage tester", "Multimeter", "Insulated screwdrivers"],
    commonMaterials: ["Wire", "Terminals", "Outlet"],
    duration: minutes(40, 75, 150),
    complexity: "complex",
    emergencyCapable: true,
    certifications: ["Licensed electrician"],
    price: syp(100000, 250000, 600000),
    relatedTrades: [],
    matchKeywords: ["spark", "شرر", "burning", "حريق", "دخان", "smoke"],
    workersTypical: 1,
    followUpWork: ["Full circuit inspection"],
  },
  {
    serviceKey: "painting.indoor.room",
    categorySlug: "painting",
    subcategory: "indoor",
    typicalProblems: ["Room paint", "Touch-up", "Color change"],
    commonCauses: ["Wear", "Stains", "Renovation finish"],
    requiredSkills: ["Surface prep", "Even coating"],
    typicalTools: ["Roller", "Brushes", "Tray", "Masking tape", "Drop cloth"],
    commonMaterials: ["Primer", "Paint", "Filler"],
    duration: days(1, 2, 3),
    complexity: "moderate",
    emergencyCapable: false,
    certifications: [],
    price: syp(200000, 500000, 1200000),
    relatedTrades: ["carpentry"],
    matchKeywords: ["paint", "طلاء", "دهان", "room", "غرفة", "bedroom"],
    workersTypical: 1,
    followUpWork: [],
  },
  {
    serviceKey: "hvac.not_cooling",
    categorySlug: "hvac",
    subcategory: "not_cooling",
    typicalProblems: ["AC not cooling", "Weak airflow"],
    commonCauses: ["Low refrigerant", "Dirty filter", "Blocked drain"],
    requiredSkills: ["AC diagnosis", "Filter service"],
    typicalTools: ["Gauge set", "Screwdrivers", "Vacuum (service)"],
    commonMaterials: ["Filter", "Refrigerant (if certified)", "Drain tablets"],
    duration: minutes(45, 90, 180),
    complexity: "moderate",
    emergencyCapable: false,
    certifications: ["HVAC refrigerant handling (when charging)"],
    price: syp(80000, 200000, 500000),
    relatedTrades: ["electrical"],
    matchKeywords: ["ac", "مكيف", "cool", "يبرد", "تبريد", "hvac"],
    workersTypical: 1,
    followUpWork: ["Electrical check if compressor fails"],
  },
  {
    serviceKey: "locksmith.lockout",
    categorySlug: "locksmith",
    subcategory: "lockout",
    typicalProblems: ["Locked out", "Lost key", "Stuck lock"],
    commonCauses: ["Lost keys", "Jammed cylinder", "Broken key"],
    requiredSkills: ["Non-destructive entry", "Cylinder service"],
    typicalTools: ["Lock picks / entry kit", "Screwdrivers"],
    commonMaterials: ["Cylinder", "Keys"],
    duration: minutes(20, 40, 75),
    complexity: "moderate",
    emergencyCapable: true,
    certifications: [],
    price: syp(50000, 120000, 300000),
    relatedTrades: ["carpentry"],
    matchKeywords: ["locked", "محبوس", "برّا", "key", "مفتاح", "lock", "قفل"],
    workersTypical: 1,
    followUpWork: ["Door alignment if carpentry related"],
  },
  {
    serviceKey: "carpentry.door.repair",
    categorySlug: "carpentry",
    subcategory: "door",
    typicalProblems: ["Door won't close", "Hinge sag", "Frame damage"],
    commonCauses: ["Loose hinges", "Swollen wood", "Misaligned strike"],
    requiredSkills: ["Door hanging", "Plane/adjust"],
    typicalTools: ["Screwdrivers", "Plane", "Drill", "Level"],
    commonMaterials: ["Hinges", "Screws", "Wood filler"],
    duration: minutes(40, 70, 120),
    complexity: "moderate",
    emergencyCapable: false,
    certifications: [],
    price: syp(60000, 140000, 320000),
    relatedTrades: ["locksmith"],
    matchKeywords: ["door", "باب", "hinge", "مفصل"],
    workersTypical: 1,
    followUpWork: [],
  },
  {
    serviceKey: "renovation.kitchen.multi",
    categorySlug: "carpentry",
    subcategory: "renovation",
    typicalProblems: ["Kitchen renovation", "Full remodel"],
    commonCauses: ["Planned remodel"],
    requiredSkills: ["Multi-trade coordination"],
    typicalTools: ["General carpentry + trade-specific"],
    commonMaterials: ["Varies by scope"],
    duration: days(5, 10, 20),
    complexity: "complex",
    emergencyCapable: false,
    certifications: [],
    price: syp(2000000, 8000000, 25000000),
    relatedTrades: ["plumbing", "electrical", "painting"],
    matchKeywords: ["renovation", "تجديد", "kitchen remodel", "مطبخ كامل"],
    workersTypical: 3,
    followUpWork: ["Snagging list", "Touch-up paint"],
  },
  {
    serviceKey: "damage.water.multi",
    categorySlug: "plumbing",
    subcategory: "water_damage",
    typicalProblems: ["Water damage", "Flood aftermath"],
    commonCauses: ["Burst pipe", "Overflow", "Roof/plumbing leak"],
    requiredSkills: ["Leak stop", "Drying assessment"],
    typicalTools: ["Pipe wrench", "Wet vac", "Moisture meter"],
    commonMaterials: ["Pipe fittings", "Sealant", "Drying equipment"],
    duration: days(2, 4, 7),
    complexity: "complex",
    emergencyCapable: true,
    certifications: [],
    price: syp(300000, 1200000, 5000000),
    relatedTrades: ["painting", "carpentry"],
    matchKeywords: ["water damage", "غرق", "flood", "رطوبة", "damage"],
    workersTypical: 2,
    followUpWork: ["Drywall", "Paint", "Floor repair"],
  },
];

const BY_KEY = new Map(
  SERVICE_KNOWLEDGE_CATALOG.map((e) => [e.serviceKey, e]),
);

export function getServiceKnowledge(serviceKey: string): ServiceKnowledgeEntry | null {
  return BY_KEY.get(serviceKey) ?? null;
}

export function listServiceKnowledgeByCategory(
  categorySlug: string,
): ServiceKnowledgeEntry[] {
  return SERVICE_KNOWLEDGE_CATALOG.filter((e) => e.categorySlug === categorySlug);
}
