/**
 * Workflow registry — extensible catalog of autonomous workflows.
 */

import type { WorkflowDefinition } from "./types";

export const WORKFLOW_CATALOG: WorkflowDefinition[] = [
  // Customer
  {
    id: "customer.suggest_missing_photos",
    nameEn: "Suggest missing photos",
    nameAr: "اقتراح صور ناقصة",
    audience: "customer",
    triggerKey: "request_incomplete",
    actionType: "suggest_missing_photos",
    module: "automation.customer",
    reversible: true,
  },
  {
    id: "customer.suggest_missing_address",
    nameEn: "Suggest missing address",
    nameAr: "اقتراح عنوان ناقص",
    audience: "customer",
    triggerKey: "request_incomplete",
    actionType: "suggest_missing_address",
    module: "automation.customer",
    reversible: true,
  },
  {
    id: "customer.remind_inactivity",
    nameEn: "Remind after inactivity",
    nameAr: "تذكير بعد عدم النشاط",
    audience: "customer",
    triggerKey: "customer_inactive",
    actionType: "remind_inactivity",
    module: "automation.customer",
    reversible: true,
  },
  {
    id: "customer.suggest_appointment_confirm",
    nameEn: "Suggest appointment confirmation",
    nameAr: "اقتراح تأكيد الموعد",
    audience: "customer",
    triggerKey: "appointment_pending",
    actionType: "suggest_appointment_confirm",
    module: "automation.customer",
    reversible: true,
  },
  {
    id: "customer.remind_review",
    nameEn: "Remind review after completion",
    nameAr: "تذكير بالمراجعة بعد الإنجاز",
    audience: "customer",
    triggerKey: "job_completed",
    actionType: "remind_review",
    module: "automation.customer",
    reversible: true,
  },
  {
    id: "customer.suggest_followup_maintenance",
    nameEn: "Suggest follow-up maintenance",
    nameAr: "اقتراح صيانة لاحقة",
    audience: "customer",
    triggerKey: "job_completed",
    actionType: "suggest_followup_maintenance",
    module: "automation.customer",
    reversible: true,
  },
  // Provider
  {
    id: "provider.auto_accept_job",
    nameEn: "Auto-accept job (opt-in)",
    nameAr: "قبول تلقائي للطلب (اختياري)",
    audience: "provider",
    triggerKey: "job_offered",
    actionType: "auto_accept_job",
    module: "automation.provider",
    reversible: true,
  },
  {
    id: "provider.reject_out_of_area",
    nameEn: "Reject outside service area",
    nameAr: "رفض خارج منطقة الخدمة",
    audience: "provider",
    triggerKey: "job_offered",
    actionType: "reject_out_of_area",
    module: "automation.provider",
    reversible: true,
  },
  {
    id: "provider.reject_outside_hours",
    nameEn: "Reject outside working hours",
    nameAr: "رفض خارج ساعات العمل",
    audience: "provider",
    triggerKey: "job_offered",
    actionType: "reject_outside_hours",
    module: "automation.provider",
    reversible: true,
  },
  {
    id: "provider.suggest_route_optimization",
    nameEn: "Suggest route optimization",
    nameAr: "اقتراح تحسين المسار",
    audience: "provider",
    triggerKey: "schedule_loaded",
    actionType: "suggest_route_optimization",
    module: "automation.provider",
    reversible: true,
  },
  {
    id: "provider.fill_schedule_gaps",
    nameEn: "Fill schedule gaps",
    nameAr: "ملء فراغات الجدول",
    audience: "provider",
    triggerKey: "schedule_loaded",
    actionType: "fill_schedule_gaps",
    module: "automation.provider",
    reversible: true,
  },
  {
    id: "provider.recommend_nearby",
    nameEn: "Recommend nearby opportunities",
    nameAr: "فرص قريبة مقترحة",
    audience: "provider",
    triggerKey: "schedule_loaded",
    actionType: "recommend_nearby",
    module: "automation.provider",
    reversible: true,
  },
  {
    id: "provider.prepare_appointment_summary",
    nameEn: "Prepare appointment summary",
    nameAr: "ملخص موعد جاهز",
    audience: "provider",
    triggerKey: "appointment_upcoming",
    actionType: "prepare_appointment_summary",
    module: "automation.provider",
    reversible: true,
  },
  {
    id: "provider.detect_overload",
    nameEn: "Detect overloaded schedule",
    nameAr: "اكتشاف جدول مثقل",
    audience: "provider",
    triggerKey: "schedule_loaded",
    actionType: "detect_overload",
    module: "automation.provider",
    reversible: true,
  },
  // Admin
  {
    id: "admin.detect_spam",
    nameEn: "Detect spam requests",
    nameAr: "كشف طلبات مزعجة",
    audience: "admin",
    triggerKey: "admin_scan",
    actionType: "detect_spam",
    module: "automation.admin",
    reversible: true,
  },
  {
    id: "admin.detect_duplicates",
    nameEn: "Detect duplicate jobs",
    nameAr: "كشف طلبات مكررة",
    audience: "admin",
    triggerKey: "admin_scan",
    actionType: "detect_duplicates",
    module: "automation.admin",
    reversible: true,
  },
  {
    id: "admin.detect_inactive_providers",
    nameEn: "Detect inactive providers",
    nameAr: "كشف مزودين غير نشطين",
    audience: "admin",
    triggerKey: "admin_scan",
    actionType: "detect_inactive_providers",
    module: "automation.admin",
    reversible: true,
  },
  {
    id: "admin.detect_suspicious",
    nameEn: "Detect suspicious behaviour",
    nameAr: "كشف سلوك مشبوه",
    audience: "admin",
    triggerKey: "admin_scan",
    actionType: "detect_suspicious",
    module: "automation.admin",
    reversible: true,
  },
  {
    id: "admin.detect_response_delays",
    nameEn: "Detect large response delays",
    nameAr: "كشف تأخيرات كبيرة في الرد",
    audience: "admin",
    triggerKey: "admin_scan",
    actionType: "detect_response_delays",
    module: "automation.admin",
    reversible: true,
  },
  {
    id: "admin.detect_shortages",
    nameEn: "Detect marketplace shortages",
    nameAr: "كشف نقص في السوق",
    audience: "admin",
    triggerKey: "admin_scan",
    actionType: "detect_shortages",
    module: "automation.admin",
    reversible: true,
  },
  // Hard safety — always blocked from auto-exec
  {
    id: "safety.payment",
    nameEn: "Payment (never auto)",
    nameAr: "دفع (لا يُنفَّذ تلقائياً)",
    audience: "system",
    triggerKey: "safety",
    actionType: "payment",
    module: "automation.safety",
    reversible: false,
    safetyBlocked: true,
  },
  {
    id: "safety.provider_suspension",
    nameEn: "Provider suspension (never auto)",
    nameAr: "إيقاف مزود (لا يُنفَّذ تلقائياً)",
    audience: "admin",
    triggerKey: "safety",
    actionType: "provider_suspension",
    module: "automation.safety",
    reversible: false,
    safetyBlocked: true,
  },
];

export function getWorkflow(id: string): WorkflowDefinition | undefined {
  return WORKFLOW_CATALOG.find((w) => w.id === id);
}

export function listWorkflowsByAudience(
  audience: WorkflowDefinition["audience"],
): WorkflowDefinition[] {
  return WORKFLOW_CATALOG.filter((w) => w.audience === audience);
}
